src/main/webapp/index.jsp, src/main/webapp/manage/notice/notice.jsp, src/main/webapp/manage/notice/notice_detail.jsp, src/main/webapp/manage/notice/notice_write.jsp, src/main/webapp/notice/notice.jsp, src/main/webapp/notice/notice_detail.jsp
=> feat : 공지사항 관리자, 사용자 ui 구현

.gitignore, src/main/webapp/assets/css/index.css, src/main/webapp/index.jsp
기존 버전에서는 swiper.js 라이브러리를 사용했음
4.4.2 버전 사용했지만 현재는 11.1.1이 최신 버전으로 팔로업 되지 않아 충돌 발생함
- next 버튼 클릭 시 버튼이 사라지는 이슈가 있었음
- 클론 코딩을 위해 가져온 코드는 uglify 처리된 상태였기에 코드 파악이 쉽지 않았음
- 4.4.2 버전의 소스코드를 찾아보았으나 실패함
- 소스코드를 찾아 수정하는 것보다 새로운 라이브러리를 찾아 사용하는 것이 더 빠를 것이라고 생각하여 slick 채택
- ref : https://kenwheeler.github.io/slick/
=> feat : 사용자 메인 페이지 carousel 추가

src/main/webapp/manage/review/review.jsp, src/main/webapp/manage/review/review_select.jsp
feat: review_select.jsp 생성(리뷰 상세보기 페이지) 아직 미완
=> fix: review_list.jsp 대신 review.jsp 파일로 관리자 리뷰 UI 대체

src/main/webapp/order/input_card_info.jsp, src/main/webapp/order/order_form.jsp
=> feat : 카드결제창 UI 추가

src/main/webapp/manage/review/review_detail.jsp, src/main/webapp/manage/review/review_my.jsp, src/main/webapp/manage/review/review_update.jsp
=> feat: 리뷰 수정 화면 추가

src/main/webapp/cart/cart.jsp, src/main/webapp/manage/order/order.jsp, src/main/webapp/manage/order/order_manage_detail.jsp, src/main/webapp/manage/order/order_manage_list.jsp, src/main/webapp/manage/refund/refund.jsp, src/main/webapp/manage/refund/refund_manage_detail.jsp, src/main/webapp/manage/refund/refund_manage_list.jsp, src/main/webapp/order/input_card_info.jsp, src/main/webapp/order/order_complete.jsp, src/main/webapp/order/order_form.jsp
feat: order_form.jsp에 카드결제 화면 추가
=> feat: order_form.jsp에 카드결제 화면 추가

src/main/java/admin/order/AdminOrderDAO.java, src/main/java/admin/order/AdminReturnDAO.java, src/main/java/order/vo/CardVO.java, src/main/java/order/vo/DeliveryVO.java, src/main/java/order/vo/OrderDetailVO.java, src/main/java/order/vo/OrderProductVO.java, src/main/java/order/vo/OrderVO.java, src/main/java/order/vo/PaymentInfoVO.java, src/main/java/order/vo/ReturnDetailVO.java, src/main/java/order/vo/ReturnVO.java, src/main/java/user/main/UserMainDAO.java, src/main/java/user/order/CartDAO.java, src/main/java/user/order/UserOrderDAO.java, src/main/java/user/order/UserReturnDAO.java, src/main/webapp/cart/cart.jsp, src/main/webapp/cart/cart_info.jsp, src/main/webapp/cart/cart_process.jsp
=> feat : 주문관리 VO, DAO 클래스 추가

src/main/java/order/vo/OrderVO.java, src/main/java/user/order/CartDAO.java, src/main/webapp/cart/cart.jsp, src/main/webapp/cart/cart_process.jsp
feat : CartDAO insert,update,delete 메소드 추가
=> feat : CartDAO insert,update,delete 메소드 추가

src/main/java/admin/dashboard/DashboardDAO.java, src/main/java/admin/dashboard/DashboardSalesVO.java, src/main/java/admin/goods/AdminGoodsDAO.java, src/main/java/user/goods/UserGoodsDAO.java, src/main/java/user/main/UserMainDAO.java, src/main/webapp/goods/category.jsp, src/main/webapp/manage/dashboard/index.jsp, src/main/webapp/manage/goods/delete_process.jsp
1. 관리자 대시보드에서 매출 관련 정보 출력
2. 사용자 페이지에서 품절 상품 보이지 않게 수정
3. 사용자 페이지 카테고리 별 검색 결과 레코드 개수 출력
=> feat : 관리자 대시보드 / 사용자 품절처리

src/main/java/admin/review/AdminReviewDAO.java, src/main/java/user/review/UserReviewDAO.java, src/main/webapp/manage/review/reviewTableAjax.jsp, src/main/webapp/manage/review/review_board_list.jsp, src/main/webapp/manage/review/review_detail_admin.jsp, src/main/webapp/manage/review/review_detail_user.jsp, src/main/webapp/manage/review/review_my_list.jsp, src/main/webapp/manage/review/review_read_frm.jsp, src/main/webapp/manage/review/review_update_process.jsp, src/main/webapp/manage/review/review_write_process.jsp, src/main/webapp/manage/review/review_write_test.jsp
=> fix: 관리자 사용자 리뷰 상세보기 이미지 오류 수정

src/main/java/order/vo/OrderVO.java, src/main/java/user/order/CartDAO.java, src/main/webapp/cart/cart.jsp, src/main/webapp/cart/cart_process.jsp, src/main/webapp/cart/insert_org_process.jsp
=> feat : 장바구니 오류 수정중, jsp 파일 추가

src/main/webapp/assets/jsp/user/header.jsp, src/main/webapp/goods/category.jsp, src/main/webapp/goods/detail.jsp, src/main/webapp/index.jsp
1. 관심 상품 등록 링크 연결 (상세페이지, 미리보기 모두)
2. 사용자 페이지 헤더 관심상품 링크 추가
=> feat : 사용자 관심상품 관련 기능

src/main/java/user/review/UserReviewDAO.java, src/main/webapp/goods/detail.jsp, src/main/webapp/manage/review/board_read_frm.jsp, src/main/webapp/manage/review/review_board_list.jsp, src/main/webapp/manage/review/review_detail_user.jsp, src/main/webapp/manage/review/review_my_list.jsp, src/main/webapp/manage/review/review_read_frm.jsp, src/main/webapp/manage/review/review_update_process.jsp, src/main/webapp/manage/review/review_write.jsp, src/main/webapp/manage/review/review_write_process.jsp
feat: detail.jsp와 리뷰 링크 연결(상품후기 작성 눌렀을 때 상품코드는 적용시켰는데
상품일련번호는 미적용..ㅠㅠ)못적용...
=> fix: 리뷰 등록, 수정 오류 수정, 관심상품 등록 오류 수정

src/main/webapp/order/order_form.jsp, src/main/webapp/order/payment_process.jsp
=> feat : 주문서 작성 기능, 카드 결제 추가

src/main/java/order/vo/CardVO.java, src/main/java/order/vo/OrderVO.java, src/main/java/order/vo/PaymentInfoVO.java, src/main/java/user/order/CartDAO.java, src/main/webapp/cart/input_process.jsp, src/main/webapp/order/order_complete.jsp, src/main/webapp/order/order_form.jsp, src/main/webapp/order/payment_process.jsp
feat : 주문완료 시 데이터베이스에 insert, update 로직 추가 , payment_process.jsp 코드 에러 발생(수정 진행중)
=> feat : 주문완료 시 데이터베이스에 insert, update 로직 추가 , payment_process.jsp 코드 에러

src/main/java/admin/order/AdminOrderDAO.java, src/main/webapp/manage/order/detail.jsp, src/main/webapp/manage/order/status_update_process.jsp
1. 상품 상태 변경시 Ajax로 비동기 데이터 조회
2. 상품 상태가 변경되도록 DAO method 구현
=> feat : 관리자 주문 상세 페이지 기능

src/main/java/user/review/UserReviewDAO.java, src/main/webapp/review/review_my_list.jsp, src/main/webapp/review/review_write.jsp, src/main/webapp/review/review_write_process.jsp, src/main/webapp/user/OrderReturn/order_list.jsp
=> fix: 리뷰 작성 상품이미지, 상품이름과 연결완료!

src/main/java/order/vo/ReturnDetailVO.java, src/main/java/user/order/CartDAO.java, src/main/java/user/order/UserOrderDAO.java, src/main/java/user/order/UserReturnDAO.java, src/main/webapp/order/order_complete.jsp, src/main/webapp/order/order_detail.jsp, src/main/webapp/order/return_detail.jsp
=> feat : 반품 상세조회 구현

src/main/webapp/review/review_read_frm.jsp
=> fix: 리뷰 수정 오류 고쳤습니다!!

src/main/webapp/assets/jsp/user/header.jsp, src/main/webapp/order/order_form.jsp
=> feat : header 링크 수정

src/main/java/user/order/CartDAO.java, src/main/webapp/order/order_complete.jsp, src/main/webapp/order/order_detail.jsp, src/main/webapp/order/order_form.jsp, src/main/webapp/order/payment_process.jsp
feat : 상품 상세 페이지에서 구매하기 버튼을 통해 주문서 작성 페이지로 넘어가는 로직 수정
=> feat : 상품 상세 페이지에서 구매하기 버튼을 통해 주문서 작성 페이지로 넘어가는 로직 수정

src/main/webapp/cart/cart.jsp, src/main/webapp/cart/cart_process.jsp, src/main/webapp/goods/detail.jsp, src/main/webapp/order/order_form.jsp
=> feat : 장바구니, 주문 에러 수정

src/main/webapp/manage/notice/notice.jsp, src/main/webapp/manage/notice/notice_delete_process.jsp, src/main/webapp/manage/notice/notice_update_process.jsp, src/main/webapp/manage/notice/notice_write_process.jsp, src/main/webapp/notice/notice.jsp
=> fix : 아이피 삭제

src/main/webapp/notice/notice.jsp
=> fix : notice.jsp ip수정

src/main/webapp/order/order_detail.jsp, src/main/webapp/order/order_form.jsp, src/main/webapp/order/return_detail.jsp
feat : 주문서 작성 페이지 내 우편번호 선택 시 정상적으로 닫히게 수정, 주문 상세조회 주문 금액 조회 수정
=> feat : 주문서 작성 페이지 내 우편번호 선택 시 정상적으로 닫히게 수정, 주문 상세조회 주문 금액 조회 수정

src/main/webapp/order/order_detail.jsp, src/main/webapp/order/return_detail.jsp
feat : 주문 상세페이지 내 상품의 리뷰 작성 가능 여부를 확인하는 기능 추가
=> feat : 주문 상세페이지 내 상품의 리뷰 작성 가능 여부를 확인하는 기능 추가

src/main/java/user/order/CartDAO.java, src/main/java/user/order/UserOrderDAO.java, src/main/webapp/order/order_detail.jsp, src/main/webapp/order/payment_process.jsp, src/main/webapp/order/return_detail.jsp
feat : 배송 정보 null 값 처리, 카드번호 중복 체크 기능 추가, 반품 상세 페이지 배송비 제외
=> feat : 배송 정보 null 값 처리, 카드번호 중복 체크 기능 추가, 반품 상세 페이지 배송비 제외

src/main/webapp/order/order_form.jsp, src/main/webapp/order/return_detail.jsp
=> feat : 주문서 작성 배송정보 null 값 처리
